version: "3"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    image: # тут нужно указать название проекта\репозитория (можно посмотреть в package.json)
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    networks:
      - webnet
    dns: 172.28.40.14 # Это актуально пока у нас проблемы с dns
    environment:
      - TERM=xterm-256color`
  nginx:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:8080"
    networks:
      - webnet
    dns: 172.28.40.14 # Это актуально пока у нас проблемы с dns
    depends_on:
      - app
networks:
  webnet:
