version: "3"
services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    image: practice-repo
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      - TERM=xterm-256color`
  nginx:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - app
networks:
  webnet:
